Repository openshift/osd-network-verifier, pull requests merged in 2021-12, with the labels that each got.

#8 adding OWNERS file
  OWNERS
Labels: lgtm

#6 feat: add basic readme for network-verifier
  README.md
Labels: approved, lgtm

#5 Add cloud image ID as a CLI option
  .gitignore
  cmd/egress/cmd.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/aws/private.go
  pkg/cloudclient/cloudclient.go
  pkg/cloudclient/gcp/gcp.go
Labels: approved, lgtm

#9 Remove panics and handle errors gracefully in egress test
  pkg/cloudclient/aws/private.go
Labels: approved, lgtm

#12 Simplifying init for cloudclient
  cmd/byovpc/cmd.go
  cmd/egress/cmd.go
  go.mod
  go.sum
  pkg/cloudclient/add_aws.go
  pkg/cloudclient/add_gcp.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/cloudclient.go
  pkg/cloudclient/gcp/gcp.go
  vendor/github.com/aws/aws-sdk-go-v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/aws/config.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/endpoints.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/credentials/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/credentials/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/credentials/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sso/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sso/api_client.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sso/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/service/sso/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_client.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/modules.txt
Labels: approved, lgtm

#15 Lengthen timeout to 1 second
  build/Dockerfile
Labels: approved, lgtm

#16 Updating readme with information about using go library for egress va…
  README.md
Labels: approved, lgtm

#17 backward compatibility with aws-sdk-go-v1
  README.md
  go.mod
  go.sum
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/cloudclient.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/context_background_go1.5.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/context_background_go1.7.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/context_go1.5.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/context_go1.9.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/env_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/example.ini
  vendor/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/static_provider.go
  vendor/github.com/aws/aws-sdk-go/internal/context/background_go1.5.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ast.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/comma_token.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/comment_token.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/doc.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/empty_token.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/expression.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/fuzz.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_lexer.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/literal_tokens.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/newline_token.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/number_helper.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/op_tokens.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/parse_error.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/parse_stack.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/sep_tokens.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/skipper.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/statement.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/value_util.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/visitor.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/walker.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ws_token.go
  vendor/github.com/aws/aws-sdk-go/internal/shareddefaults/ecs_container.go
  vendor/github.com/aws/aws-sdk-go/internal/shareddefaults/shared_config.go
  vendor/github.com/aws/aws-sdk-go/internal/sync/singleflight/LICENSE
  vendor/github.com/aws/aws-sdk-go/internal/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, lgtm

#19 feat: add deploy scripts
  .gitignore
  Makefile
  build/Dockerfile
  build/bin/network-validator.go
  hack/app_sre_build_deploy.sh
  hack/app_sre_build_push.sh
  hack/app_sre_pr_check.sh
  project.mk
  standard.mk
Labels: approved, lgtm

#21 Making image-id optional
  cmd/egress/cmd.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/aws/private.go
Labels: approved, lgtm

#24 Implement configurable tags for cloud resources
  README.md
  cmd/byovpc/cmd.go
  cmd/egress/cmd.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/aws/private.go
  pkg/cloudclient/cloudclient.go
  pkg/cloudclient/gcp/gcp.go
Labels: approved, lgtm

#18 add mock definition
  pkg/cloudclient/mock_cloudclient/mock_cloudclient.go
Labels: approved

#26 Use ocm-sdk-go logger interface and stdout implementation
  cmd/byovpc/cmd.go
  cmd/egress/cmd.go
  cmd/root.go
  go.mod
  go.sum
  main.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/aws/private.go
  pkg/cloudclient/cloudclient.go
  pkg/cloudclient/gcp/gcp.go
Labels: approved, lgtm

#28 reduce userdata script output
  build/config/config.yaml
  pkg/cloudclient/aws/private.go
Labels: approved, lgtm

#27 Wait for verification that userdata script has completed and move to nitro instance type
  cmd/egress/cmd.go
  pkg/cloudclient/aws/private.go
Labels: approved, lgtm

#32 Fix makefile go flags
  Makefile
Labels: approved, lgtm

#30 cross-platform userdata
  build/bin/network-validator.go
  build/config/config.yaml
  cmd/egress/cmd.go
  config/userdata.yaml
  hack/app_sre_build_push.sh
  pkg/cloudclient/aws/private.go
Labels: approved, lgtm

#31 Adds instance type as CLI option and verifies hypervisor is nitro
  cmd/byovpc/cmd.go
  cmd/egress/cmd.go
  pkg/cloudclient/aws/aws.go
  pkg/cloudclient/aws/private.go
  pkg/cloudclient/cloudclient.go
  pkg/cloudclient/gcp/gcp.go
Labels: approved, lgtm
