Repository openshift/osd-network-verifier, pull requests merged in 2024-10, with the labels that each got.

#272 [OSD-25046]add egress verfiy for zero egress HCP cluster
  cmd/egress/cmd.go
  pkg/data/cloud/platform.go
  pkg/data/cpu/cpu.go
  pkg/data/egress_lists/aws-hcp-zeroegress.yaml
  pkg/data/egress_lists/egress_lists.go
  pkg/probes/curl/curl_json.go
  pkg/probes/legacy/legacy.go
  pkg/probes/package_probes.go
  pkg/verifier/aws/aws_verifier.go
  pkg/verifier/aws/aws_verifier_test.go
  pkg/verifier/aws/entry_point.go
  pkg/verifier/gcp/gcp_verifier.go
Labels: approved, lgtm

#274 OSD-25873: Removing unused endpoints from egress lists
  pkg/data/egress_lists/aws-classic.yaml
  pkg/data/egress_lists/aws-hcp.yaml
  pkg/data/egress_lists/gcp-classic.yaml
Labels: approved, lgtm, jira/valid-reference

#275 OSD-25868: Adds `aws-hosted-cp` as a valid Platform name
  pkg/data/cloud/platform.go
  pkg/data/cloud/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#269 Add transparant and explicit proxy terraform scripts
  README.md
  examples/aws/terraform/vpc-proxied-explicit/README.md
  examples/aws/terraform/vpc-proxied-explicit/assets/Caddyfile.tpl
  examples/aws/terraform/vpc-proxied-explicit/assets/mitmproxy-sysctl.conf
  examples/aws/terraform/vpc-proxied-explicit/assets/mitmproxy.service
  examples/aws/terraform/vpc-proxied-explicit/assets/userdata.yaml.tpl
  examples/aws/terraform/vpc-proxied-explicit/main.tf
  examples/aws/terraform/vpc-proxied-explicit/terraform.tfvars.example
  examples/aws/terraform/vpc-proxied-explicit/variables.tf
  examples/aws/terraform/vpc-proxied-transparent/README.md
  examples/aws/terraform/vpc-proxied-transparent/assets/Caddyfile.tpl
  examples/aws/terraform/vpc-proxied-transparent/assets/mitmproxy-sysctl.conf
  examples/aws/terraform/vpc-proxied-transparent/assets/mitmproxy.service
  examples/aws/terraform/vpc-proxied-transparent/assets/userdata.yaml.tpl
  examples/aws/terraform/vpc-proxied-transparent/main.tf
  examples/aws/terraform/vpc-proxied-transparent/terraform.tfvars.example
  examples/aws/terraform/vpc-proxied-transparent/variables.tf
Labels: approved, lgtm

#276 Add joshbranham as a reviewer
  OWNERS
Labels: approved, lgtm

#278 update the comments for the ensurePrivate flag
  pkg/probes/curl/curl_json.go
  pkg/verifier/aws/entry_point.go
Labels: approved, lgtm

#279 (OSD-25668) Update documentation to include new Platform interface
  README.md
  docs/aws/aws.md
  docs/gcp/gcp.md
Labels: approved, lgtm

#277 OSD-25930: Corrects endpoint mistake
  pkg/data/egress_lists/aws-classic.yaml
  pkg/data/egress_lists/aws-hcp.yaml
  pkg/data/egress_lists/gcp-classic.yaml
Labels: approved, lgtm, jira/valid-reference

#280 OSD-20513: Add support for the `--noproxy` directive in `curl`
  cmd/egress/cmd.go
  integration/go.mod
  integration/go.sum
  pkg/probes/curl/curl_json_test.go
  pkg/probes/curl/systemd-template.sh
  pkg/probes/curl/userdata-template.yaml
  pkg/proxy/proxy.go
  pkg/verifier/aws/entry_point.go
  pkg/verifier/gcp/entry_point.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#283 Fix default PlatformType in GCP entrypoint
  pkg/verifier/gcp/entry_point.go
Labels: approved, lgtm
