Repository openshift/osd-network-verifier, pull requests merged in 2024-03, with the labels that each got.

#224 added --force-temp-security-group flag
  cmd/egress/cmd.go
  pkg/verifier/aws/aws_verifier.go
  pkg/verifier/aws/entry_point.go
  pkg/verifier/package_verifier.go
Labels: approved, lgtm

#225 Update Docs and example of using new force-temp-security-group flag
  docs/aws/aws.md
Labels: approved, lgtm

#223 Update platform type names
  RELEASE.md
  cmd/egress/cmd.go
  docs/aws/aws.md
  docs/gcp/gcp.md
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, lgtm

#226 fix leaking SG group issue
  go.mod
  go.sum
  pkg/clients/aws/aws.go
  pkg/mocks/mock_aws.go
  pkg/verifier/aws/aws_verifier_test.go
  pkg/verifier/aws/entry_point.go
Labels: approved, tide/merge-method-squash, lgtm

#227 Dependency updates
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: approved, tide/merge-method-squash, lgtm, kind/dependency-change
