Repository openshift/osd-network-verifier, pull requests merged in 2025-01, with the labels that each got.

#294 Update GCP egress list for network-verifier
  pkg/data/egress_lists/gcp-classic.yaml
Labels: approved, tide/merge-method-squash, lgtm

#258 allow custom dns query
  pkg/verifier/aws/aws_verifier.go
Labels: approved, lgtm, ok-to-test

#295 Properly set proxy env vars in systemd curl probe
  pkg/probes/curl/systemd-template.sh
Labels: approved, lgtm

#298 OSD-27967: add missing Quay endpoints to ROSA HCP egress list
  pkg/data/egress_lists/aws-hcp.yaml
Labels: approved, lgtm, jira/valid-reference

#297 OSD-27965: Update GCP Egress List to properly reflect documentation
  pkg/data/egress_lists/gcp-classic.yaml
Labels: approved, lgtm, jira/valid-reference

#296 OSD-27962: Removing references to Splunk Forwarder tcpout
  pkg/data/egress_lists/aws-classic.yaml
  pkg/data/egress_lists/gcp-classic.yaml
Labels: approved, lgtm, jira/valid-reference

#299 OSD-27966: Clean up egress list for ROSA Classic/OSD-AWS
  pkg/data/egress_lists/aws-classic.yaml
Labels: approved, lgtm, jira/valid-reference
